package com.bingbaihanji.bdec.decompiler.ast;

public enum AstKind {
    COMPILATION_UNIT,
    TYPE_DECLARATION,
    FIELD_DECLARATION,
    METHOD_DECLARATION,
    BLOCK,
    IF,
    LOOP,
    SWITCH,
    TRY,
    THROW,
    RETURN,
    BREAK,
    CONTINUE,
    EXPRESSION_STATEMENT,
    ASSIGNMENT,
    VARIABLE,
    LITERAL,
    UNARY,
    BINARY,
    METHOD_INVOCATION,
    FIELD_ACCESS,
    ARRAY_ACCESS,
    NEW_OBJECT,
    NEW_ARRAY,
    CAST,
    CONDITIONAL,
    LAMBDA
}
