package com.bingbaihanji.bdec.ast.rewrite;

import com.bingbaihanji.bdec.DecompileContext;
import com.bingbaihanji.bdec.ast.AstNode;
import com.bingbaihanji.bdec.ast.CompilationUnit;
import com.bingbaihanji.bdec.ast.TypeDeclaration;
import com.bingbaihanji.bdec.ast.stmt.FieldDeclaration;
import com.bingbaihanji.bdec.ast.stmt.MethodDeclaration;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Detects Java records (ACC_RECORD flag) and restores the
 * {@code record} keyword, canonical constructor, and component list.
 *
 * <p>Pattern:
 * <pre>
 *   final class Point extends java/lang/Record {
 *       private final int x;
 *       private final int y;
 *       Point(int x, int y) { this.x = x; this.y = y; }  // canonical ctor
 *       int x() { return x; }  // synthetic accessor
 *       int y() { return y; }  // synthetic accessor
 *       // toString/hashCode/equals overrides or synthetic
 *   }
 *
 *   → record Point(int x, int y) { }
 * </pre>
 *
 * <p>Inspired by Vineflower's {@code RecordHelper}.
 */
public class RecordRewriter implements RewriteRule {

    /** ACC_RECORD flag (0x0010 in class context, distinct from ACC_FINAL 0x0010). */
    private static final int ACC_RECORD = 0x0010;

    private static final Set<String> SYNTHETIC_RECORD_METHODS = Set.of(
            "toString", "hashCode", "equals");

    private static final java.util.Map<String, Integer> RECORD_METHOD_PARAM_COUNT =
            java.util.Map.of("toString", 0, "hashCode", 0, "equals", 1);

    @Override
    public String name() {return "record";}

    @Override
    public CompilationUnit rewrite(CompilationUnit unit, DecompileContext context) {
        List<TypeDeclaration> types = new ArrayList<>();
        for (TypeDeclaration td : unit.types()) {
            types.add(rewriteType(td));
        }
        return new CompilationUnit(unit.packageName(), unit.imports(), types);
    }

    private TypeDeclaration rewriteType(TypeDeclaration td) {
        if (!isRecord(td)) {
            return td;
        }

        // Collect record component field names
        Set<String> componentFields = new HashSet<>();
        List<String> componentNames = new ArrayList<>();
        for (AstNode m : td.children()) {
            if (m instanceof FieldDeclaration fd && isPrivateFinal(fd)) {
                componentFields.add(fd.name());
                componentNames.add(fd.name());
            }
        }

        // Filter out synthetic members and component fields
        List<AstNode> members = new ArrayList<>();
        for (AstNode m : td.children()) {
            if (m instanceof FieldDeclaration fd) {
                // Remove component fields — they are auto-generated by the record keyword
                if (componentFields.contains(fd.name())) {
                    continue;
                }
            }
            if (m instanceof MethodDeclaration md) {
                if (isCanonicalConstructor(md, componentFields)) {
                    continue;
                }
                if (isSyntheticAccessor(md, componentFields)) {
                    continue;
                }
                // Filter synthetic record methods: toString(), hashCode(), equals(Object)
                Integer expectedParams = RECORD_METHOD_PARAM_COUNT.get(md.name());
                if (expectedParams != null && md.parameterNames().length == expectedParams) {
                    continue;
                }
            }
            members.add(m);
        }

        // Build type parameters from components: "int x, int y"
        List<String> recordComponents = new ArrayList<>();
        for (String name : componentNames) {
            // Find the field type
            for (AstNode m : td.children()) {
                if (m instanceof FieldDeclaration fd && name.equals(fd.name())) {
                    recordComponents.add(fd.type().displayName() + " " + name);
                    break;
                }
            }
        }

        // Records don't show "extends Record" — null out the super name
        return new TypeDeclaration(td.accessFlags() & ~ACC_RECORD,
                td.simpleName(), "record", null,
                td.interfaceNames(), recordComponents, members);
    }

    private boolean isRecord(TypeDeclaration td) {
        // ACC_RECORD shares the ACC_FINAL bit (0x0010) in class context.
        // Records MUST extend java.lang.Record. The super name in TypeDeclaration
        // is the simple name (e.g., "Record"), not the full internal name.
        if ((td.accessFlags() & ACC_RECORD) == 0) {
            return false;
        }
        String superName = td.superName();
        return "Record".equals(superName) || "java/lang/Record".equals(superName);
    }

    private boolean isPrivateFinal(FieldDeclaration fd) {
        int flags = fd.accessFlags();
        return (flags & 0x0002) != 0 && (flags & 0x0010) != 0; // private + final
    }

    /** Check if a constructor is the canonical (all-fields) constructor. */
    private boolean isCanonicalConstructor(MethodDeclaration md, Set<String> fields) {
        // Constructor name may be "<init>" or the class name (from AstBuilder name resolution)
        if (!"<init>".equals(md.name())) {
            // If not <init>, check if it's a constructor by verifying void return
            if (md.returnType() != null && md.returnType().kind() != com.bingbaihanji.bdec.type.TypeKind.VOID) {
                return false; // regular method, not a constructor
            }
        }
        if (md.parameterNames().length != fields.size()) {
            return false;
        }
        for (String param : md.parameterNames()) {
            if (!fields.contains(param)) {
                return false;
            }
        }
        return true;
    }

    /** Check if a method is a synthetic accessor (name matches a field). */
    private boolean isSyntheticAccessor(MethodDeclaration md, Set<String> fields) {
        if (md.parameterNames().length != 0) {
            return false;
        }
        return fields.contains(md.name());
    }
}
